### ISSUE TITLE
All API endpoints for Judgements, Verdicts and Indicators working

### ISSUE THREAD

**Issue by craigbro** [threatgrid/ctia#19]
We want all endpoints for judgements, verdicts and indicators to be functional.  This does NOT include all TTP, Campaign and Actor endpoints.

**Comment by craigbro** [comment]
@Steve please update this with the missing APi endpoints.

**Comment by polygloton** [comment]
## TODO API endpoints

- [ ] /indicator/:id/judgements
- [ ] /indicator/:id/sightings
- [ ] /indicator/:id/campaigns
- [ ] /indicator/:id/coas
- [ ] /indicator/:id/ttps

**Comment by yogsototh** [comment]
So our discussion yesterday concluded we should only provide the reverse the searching abilities.

So the routes  `/indicator/:id/{judgements,campaigns,coas,ttps}` should be removed.
Should we then provide the following routes?

- `/judgements/:id/indicators` all indicators referencing some judgement.
- `/campaign/:id/indicators` 
- `/coas/:id/indicators`
- `/ttps/:id/indicators`

And maybe a `/indicators` route able to deal with more complex queries?

**Comment by polygloton** [comment]
I think that we do add those routes (add all reverse search routes).

**Comment by polygloton** [comment]
See also #220.

**Comment by craigbro** [comment]
Yes, we should add those reverse routes.
