### ISSUE TITLE
Semantically valuable IDs

### ISSUE THREAD

**Issue by polygloton** [threatgrid/ctia#212]
- [x] IDs are URLs that match the entity GET route
- [x] Users can optionally submit a semantically valuable ID
  - [x] CTIA will convert the user submitted string into a URL to the entity
  - [x] String should be URL encoded
- [x] If user supplies an ID, don't prepend the type to it (its already in the URL)

**Comment by polygloton** [comment]
TODO:
- [ ] Update Indicator import script so that is uses meaningful URLs

**Comment by polygloton** [comment]
See also #169

**Comment by craigbro** [comment]
This issue is not closed, not util the following tests pass:

## Objects always use full URIs as IDs:
1. submit a judgement with no ID:
2. Retrieve that judgement, and the id field should be the same url you retrieved the object from

## URI resolution is used when "short form URIs" are encountered
1. submit a judgement with a RelatedIndicator uses a short form URI
2. Retrieve that judgement, the RelatedIndicator should now have a full URI 

## No more "uri" field from the BaseEntity

## Cannot create an object, or update it to a URI that is NOT on the current server
1. When we POST an object, the id of object cannot be a URI from a different host/domain

## Normal create/update doesn't allow changing an ID
1. Create Judgement with an ID set, throw an error

## Import allows create/update with an ID, using URI dereferences
1. Import judgmenet with a short form URI
2. Import Judgmeent with a full URI
3. Import Judgement with a full URI on a difference host, or entity, and fail

**Comment by polygloton** [comment]
Breaking up this issue; It is too big.  Once all of these are checked off, this issue can be closed.  Maybe we should do some acceptance testing and verify that regression tests are in place too.

## Objects always use full URIs as IDs:
- [ ] Handled by PR #418 

## URI resolution is used when "short form URIs" are encountered
We had a meeting on 9/15/2016 and decided to return errors instead of munging the data into a full URI.
- [ ] Supported by threatgrid/ctim#58
- [ ] Work to be done in #419 

## No more "uri" field from the BaseEntity
- [ ] Work to be done in threatgrid/ctim#57
- [ ] Use new CTIM version in CTIA (from above changes)

## Cannot create an object, or update it to a URI that is NOT on the current server
- [ ] Work to be done in #421 

## Normal create/update doesn't allow changing an ID
- [X] Current behavior (requires a special credential)

## Import allows create/update with an ID, using URI dereferences
- [ ] Work to be done in #420
