### ISSUE TITLE
Data flows from checksum to malware

### ISSUE THREAD

**Issue by polygloton** [threatgrid/ctia#226]
Be able to traverse entity data from file checksum to malware description.

In a sandbox
- [ ] Load indicators from TG (See #211).
- [ ] Load high-confidence sample TTPs for indicators from TG (See #224)
- [ ] Create judgements linked to indicators (See #225).

Then you can traverse from a checksum to a malware TTP.
