### ISSUE TITLE
Elasticsearch Improvements

### ISSUE THREAD

**Issue by gbuisson** [threatgrid/ctia#457]
In order to consider production grade support for ES we need:

- [x] Alias based Index access #458 
- [x] Time sliced Store Indexes #459 
- [x] Mappings split per index, using templates #460 
- [ ] Routing support #461
